name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: antlr4-runtime-playground
      tagName: v1.0.0
      mingwTargetZip: antlr4-runtime-playground-${{ github.ref_name }}-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip
    steps:
        - uses: actions/checkout@v3
        
        - name: curl jdk
          shell: bash
          run: |
            curl 'https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-debugimage_x64_windows_hotspot_16.0.2_7.zip' \
              -H 'authority: github.com' \
              -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
              -H 'accept-language: en-US,en;q=0.9' \
              -H 'cookie: _octo=GH1.1.1407610412.1679806457; preferred_color_mode=light; tz=Asia%2FShanghai; _device_id=0f2c7c936f98dac257d5b7825286bff2; has_recent_activity=1; user_session=qDYjd9-Yh0_AUv4lEP0x49a0ajF64a_Mi1eLdBnaJarr-oIX; __Host-user_session_same_site=qDYjd9-Yh0_AUv4lEP0x49a0ajF64a_Mi1eLdBnaJarr-oIX; tz=Asia%2FShanghai; color_mode=%7B%22color_mode%22%3A%22light%22%2C%22light_theme%22%3A%7B%22name%22%3A%22light%22%2C%22color_mode%22%3A%22light%22%7D%2C%22dark_theme%22%3A%7B%22name%22%3A%22dark%22%2C%22color_mode%22%3A%22dark%22%7D%7D; logged_in=yes; dotcom_user=dirkarnez; _gh_sess=5MjsT90h8UoyGSBW8d20KvCXnxW0qTVpO0DLJ3DmY4KlkaamuNs80C4nHG12ULxz1EVeV%2B3enHuZQqn4EJVyBndNe3bS6VhSilq2Sa4zBEurWz65UwSL5EcBhQ1YIqpKmMtlhAnUBsR7KJKAsPGRGAHgP5O2JWwGmZ%2BrmRJMdP6YsZ69PEV2uNfs8dgOTszOQJiYEZUnhQkcVggsqqfGYIX%2BhqazliFIiKdSR5RGgjkN1WKlfbiOavK9s%2FtH%2BTkQpRZmXXclbefG2YHbnG0%2B8UrfBsq3sofd3NAHPyMdJ%2B%2BYR99O4A70Qsf3dZHytLq2wKQfhmtItMSOPnlrYztZLZ2jMBvMun9vd7yKRhOC10OA%2BfNbduB%2BAC0RVbuNrxVZtVQRXuwFL3X2x1k3DFrm3rKlR46R%2FMYpUqQfXHuBhjXW1cpO3QHODuVB0swn8HAiXvyQ4Im3B4%2BxygrAOebrtXYjlMNHBaaQE4FeRpmcycOr3LQbmGZWu%2BXhRIi0q%2Bndl4DIzscbDnS5hLf%2BbAHzpZQDN2YnfG%2FbJ7f%2BsL9F0u6xyDdn8CnSkbJoCO8pcrrlxJYAuClYZ%2Fygji06bXedLpvF5Q%2F%2FQRuAmPzM6CUcGd8XP%2Bf8UhcNLQoNHXTKIr8%2FbUxN73WLpB4Vf%2BKU0zzsuJ79qieXpYwUalNwH%2BA5JIRapjzYAqL%2FYr9SarBZ9wx0aGwL9dq5vQzBNAJwr6BfgZ6GQ%2FwvisxnsfB5oIJInUE5QZdh24lS5XCfw%2FaT09gXNv%2BmDM4ZUC2n%2Be9P9ijzQAeg9CmDPwaKb1V4Qc6sPOACeAtncaTQYi11D6jert35nk7hzGPVLEivq0BqJOsKGDCGSrjctPgkB04vfjiUn%2Fkp--SDVGpIUg6jNfkQcW--qrIadC2%2B%2FfTW5ZMhkhAR8g%3D%3D' \
              -H 'referer: https://github.com/adoptium/temurin16-binaries/releases/tag/jdk-16.0.2%2B7' \
              -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"' \
              -H 'sec-ch-ua-mobile: ?0' \
              -H 'sec-ch-ua-platform: "Windows"' \
              -H 'sec-fetch-dest: document' \
              -H 'sec-fetch-mode: navigate' \
              -H 'sec-fetch-site: same-origin' \
              -H 'sec-fetch-user: ?1' \
              -H 'upgrade-insecure-requests: 1' \
              -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' \
              --compressed && \
              7z.exe x OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7.zip -o"OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7"
            
        - name: curl cmake-3.22.2-windows-x86_64.zip
          shell: cmd
          run: |
            curl https://github.com/dirkarnez/antlr4-runtime-prebuilt/releases/download/v4.11.1/antlr4-runtime-v4.11.1-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip -L -O -J &&^
            dir &&^
            7z.exe x antlr4-runtime-v4.11.1-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip -o"antlr4-runtime-v4.11.1-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4"
            
        - name: curl cmake-3.22.2-windows-x86_64.zip
          shell: cmd
          run: |
            curl https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip -L --output cmake-3.22.2-windows-x86_64.zip &&^
            dir &&^
            7z.exe x cmake-3.22.2-windows-x86_64.zip
          
        - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
          shell: cmd
          run:  |
            curl https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-15.0.7-10.0.0-ucrt-r4/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip -L -O -J &&^
            7z.exe x winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip
            
        - name: set PATH, check mingw version, cmake generate, build and install
          shell: cmd
          run: |
            set PATH=^
            ${{ github.workspace }}\mingw64;^
            ${{ github.workspace }}\mingw64\bin;^
            ${{ github.workspace }}\PortableGit-2.38.1-64-bit\bin;^
            ${{ github.workspace }}\cmake-3.22.2-windows-x86_64\bin;^
            ${{ github.workspace }}\OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7\jdk-16.0.2+7\bin;^
            C:\Windows\System32;
            set CD_LINUX=%CD:\=/%
            gcc --version &&^
            java --version &&^
            cmake.exe -G "MinGW Makefiles" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DBUILD_SHARED_LIBS=OFF ^
            -Dantlr4-generator_DIR="%CD_LINUX%/antlr4-runtime-v4.11.1-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4/lib/cmake/antlr4-generator" ^
            -Dantlr4-runtime_DIR="%CD_LINUX%/antlr4-runtime-v4.11.1-winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4/lib/cmake/antlr4-runtime" ^
            -B./cmake-build &&^
            cd cmake-build &&^
            cmake --build .
            
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: 'zip'
            directory: "cmake-build"
            path: antlr4-runtime-playground.exe
            filename: "${{ env.mingwTargetZip }}"
            
        - name: Release prebuilt
          uses: ncipollo/release-action@v1
          with:
            artifacts: "cmake-build/${{ env.mingwTargetZip }}"
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}     
